// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWPXNzVY-lOi9-8wxzsLQnWhbETIGAVbw',
    appId: '1:441237916030:web:e28567e2e69c05d7c04b2f',
    messagingSenderId: '441237916030',
    projectId: 'old-care-project',
    authDomain: 'old-care-project.firebaseapp.com',
    storageBucket: 'old-care-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb01G1uZfmpr1fk-etP6guudbSeiTB4rc',
    appId: '1:441237916030:android:3da616bf1fd38f5dc04b2f',
    messagingSenderId: '441237916030',
    projectId: 'old-care-project',
    storageBucket: 'old-care-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSYzG3PqwOCvtKP65L1ckVEBIZUkvwqBk',
    appId: '1:441237916030:ios:3c9f30d47a7d6723c04b2f',
    messagingSenderId: '441237916030',
    projectId: 'old-care-project',
    storageBucket: 'old-care-project.firebasestorage.app',
    iosBundleId: 'com.example.oldcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSYzG3PqwOCvtKP65L1ckVEBIZUkvwqBk',
    appId: '1:441237916030:ios:3c9f30d47a7d6723c04b2f',
    messagingSenderId: '441237916030',
    projectId: 'old-care-project',
    storageBucket: 'old-care-project.firebasestorage.app',
    iosBundleId: 'com.example.oldcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWPXNzVY-lOi9-8wxzsLQnWhbETIGAVbw',
    appId: '1:441237916030:web:5a6db5c44f4f1c17c04b2f',
    messagingSenderId: '441237916030',
    projectId: 'old-care-project',
    authDomain: 'old-care-project.firebaseapp.com',
    storageBucket: 'old-care-project.firebasestorage.app',
  );
}
